title: "Diego Palacios Farías"
description: "Associate Professor | Social Network Analysis | Adolescence | Peer relations | Substance use | Mental health"
url: "https://diegopalaciosf.github.io"
baseurl: ""
last_updated_label: "April 25, 2026"

remote_theme: "academicpages/academicpages.github.io@master"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

locale: "en-US"
markdown: kramdown

author:
  name: "Diego Palacios Farias"
  avatar: "/images/Diego_Palacios.jpg" 
  #avatar_url: "/images/profile.png"
# IMPORTANT: publish pages stored in _pages
include:
  - _pages

defaults:
  - scope:
      path: ""
    values:
      author: diego
      author_profile: true
# Default for publications collection
  - scope:
      type: publications
    values:
      author: diego
      author_profile: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
